language: node_js
os: linux
dist: xenial
node_js:
  - 8
sudo: required
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
  - node_modules
env:
  - TRAVIS_CI=true

before_install:
  # Symlink closure library used by test/jsunit
  - ln -s $(npm root)/google-closure-library ../closure-library

before_script:
  - export DISPLAY=:99.0
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then ( tests/scripts/setup_linux_env.sh ) fi
  - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then ( tests/scripts/setup_osx_env.sh ) fi
  - sleep 2

script:
  - set -x
  - npm test
  - cd tests/compile; compile.sh; cd ../..

before_deploy:
  - npm i -g

deploy:
  provider: npm
  email: kindscript@microsoft.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    branch: develop
